### ISSUE TITLE
`create': undefined method `networks' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by bacongobbler** [nathansamson/docl#7]
I keep seeing this more and more often... seems sporadic, but it'd be nice to nail this down.

```
$ docl create foobar coreos-stable 4GB nyc3 --key=~$SSH_ID --private-networking --user-data=../coreos/user-data --wait
/Library/Ruby/Gems/2.0.0/gems/docl-0.0.4/lib/docl/cli.rb:124:in `create': undefined method `networks' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/docl-0.0.4/bin/docl:5:in `<top (required)>'
	from /usr/bin/docl:23:in `load'
	from /usr/bin/docl:23:in `<main>'
```

**Comment by nathansamson** [comment]
Are your droplets created correctly? It seems there might be a problem with
response from DO...

Nathan

**Comment by bacongobbler** [comment]
No. The droplet fails to provision. It's probably something on DO's end. I'll try a raw response and see if we can nail it down.
